name: "Dependencies"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependency-submission:
    name: "Submit Dependency Graph"
    runs-on: ubuntu-latest

    permissions:
      # The Dependency Submission API requires write permission.
      contents: write

    steps:

      - name: "Checkout sources"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: "Set up Java"
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          distribution: 'temurin'
          java-version-file: '.java-version'

      - name: "Generate and submit dependency graph"
        # Note: this `uses: gradle/actions/setup-gradle@v3` under the hood.
        uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
