name: "Merge Checks"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "Build Project"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}

    permissions:
      contents: read

    steps:

      - name: "Checkout sources"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: "Set up Java"
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: ${{ (runner.os == 'macOS' && runner.arch == 'ARM64') && 'zulu' || 'temurin' }}
          java-version-file: '.java-version'

      - name: "Setup gradle"
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6

      - name: "Run Gradle tasks"
        run: ./gradlew build publishToMavenLocal

      - name: "Upload 'Test Report (${{ matrix.os }})' artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: success() || failure()
        with:
          name: 'Test Report (${{ matrix.os }})'
          path: |
            build/reports/tests/allTests/
